### PR TITLE
Adding Rspec tests for random bounding box

### PR DESCRIPTION
**Pull request by TheLucasMoore**
Hi there. I added a test for the randomly generated bounding boxes and notes about my research into why I think the tests were breaking down. 

I published the gem to version 0.2.1 as well.

### CODE REVIEW

**Comment by onyxraven** [comment]
Thanks!

I think there is possibly still some edge cases when dealing with the coordinate border cases and bounding boxes.

**Comment by onyxraven** [comment]
Since this is owned by Ibotta, do you mind adding me to the rubygems owners?

**Comment by TheLucasMoore** [comment]
@onyxraven I just added you. Let me know if that worked.

**Comment by onyxraven** [comment]
yep, thanks!

**Pull request merged**
